name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: copy to remote
      uses: actions/checkout@v3

    - name: ssh keys
      run: |
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/dccc_deploy
        chmod 600 ~/.ssh/dccc_deploy
        ssh-add ~/.ssh/dccc_deploy

    - name: connection test
      run: |
      ssh ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} ls -l ~/

    - name: copy files
      run: |
        rsync -avz --progress ./ ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:/home/${{secrets.REMOTE_USER}}/workflow_test

    
