name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
env:
  REMOTE_HOST: 104.248.234.138
  REMOTE_DIR: /home/matt/workflow_test/
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: src/
        remote_path: ${{ secrets.REMOTE_DIR }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
