name: Deploy to Digital Ocean

on:
  push:
    branches: [ master ]

env:
  REMOTE_HOST: 104.248.234.138
  REMOTE_DIR: /home/matt/workflow_test/
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  setup_ssh_keys:
    runs-on: ubuntu-latest
    steps:
      
      - name: Add public key to authorized_keys
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

  copy_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Copy files via SCP
        run: |
          scp -r . ${REMOTE_HOST}:${REMOTE_DIR}
