name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: ssh keys
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/dccc_deploy.pub
        chmod 600 ~/.ssh/dccc_deploy
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/dccc_deploy
        ssh-keyscan -H ${{secrets.REMOTE_HOST}} >> ~/.ssh/known_hosts

    - name: copy files
      run: |
        rsync -avz --progress ./ ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:/home/${{secrets.REMOTE_USER}}/workflow_test

    
