name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: start ssh agent
      run: |
        eval $(ssh-agent -s) &&
        mkdir -p ~/.ssh &&
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa &&
        ssh-add ~/.ssh/id_rsa &&
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

    - name: copy files
      run: |
        rsync -rav ./* --exclude=".*" ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{secrets.REMOTE_DEST}}

    - name: set permissions on remote
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -t -o RemoteCommand="echo '${{secrets.SUDO_PW}}' | sudo -S chown -R www-data:www-data ${{secrets.REMOTE_DEST}}" &&
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -t -o RemoteCommand="echo '${{secrets.SUDO_PW}}' | sudo -S chmod 755 ${{secrets.REMOTE_DEST}}"