name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: copy files
      uses: pierrickdelrieu/scp-action@v0.1.0
      with:
        host: ${{secrets.REMOTE_HOST}}
        ssh_port: 22
        ssh_username: ${{secrets.REMOTE_USER}}
        ssh_key: ${{secrets.SSH_PRIVATE_KEY}}
        source_dir: .
        destination_dir: ~/workflow_test
        rm: true
    
