name: Deploy to Digital Ocean

on:
  push:
    branches: [ master ]

env:
  REMOTE_HOST: 104.248.234.138
  REMOTE_DIR: /home/matt/workflow_test/
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add public key to authorized_keys
        run: |
          eval $(ssh-agent)
          echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files via SCP
        run: |
          scp -r . ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}
