name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: copy to remote
      uses: actions/checkout@v2

    - name: start ssh agent
      run: |
        eval $(ssh-agent -s) &&
        mkdir -p ~/.ssh &&
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa &&
        ssh-add ~/.ssh/id_rsa
      
    - name: copy files
      run: |
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts &&
        scp *.php ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/workflow_test &&
        scp *.css ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/workflow_test &&
        scp -r styles ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/workflow_test &&
        chown -R www-data:www-data ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:/home/${{secrets.REMOTE_USER}}/workflow_test &&
        chmod 755 ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:/home/${{secrets.REMOTE_USER}}/workflow_test